[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "versioningit~=0.3.0", "wheel"]

[tool.versioningit]
[tool.versioningit.vcs]
default-tag = "0.0.0"
match = ["exemplary/v*"]
method = "git"

[tool.versioningit.tag2version]
rmprefix = "exemplary/v"
